name: dartlero
version: 0.0.5
author: Dzenan Ridjanovic <dzenanr@gmail.com>
description: Dartlero is a model framework for educational purposes.
homepage: http://ondart.me/
dependencies:
  unittest: any
