name: dartlero
version: 1.0.5
author: Dzenan Ridjanovic <dzenanr@gmail.com>
description: dartlero is a model framework for educational purposes
homepage: https://github.com/dzenanr/dartlero
documentation: http://ondart.me/
environment:
  sdk: '>=1.10.0 <2.0.0'
dependencies:
  test: ^0.12.0
