name: dartlero
version: 1.0.1
author: Dzenan Ridjanovic <dzenanr@gmail.com>
description: dartlero is a model framework for educational purposes
homepage: http://ondart.me/
environment:
  sdk: '>=0.8.10+8 <2.0.0'
dependencies:
  unittest: '>=0.9.0 <0.10.0'
